HW1
piklin/adv_cpp pull request #1
Opened 2020-04-02 17:07 UTC by piklin

Лучше поздно, чем никогда!

2020-04-02 17:56 UTC, smirnov-vs commented
Привет, assigned ставит преподаватель по регламенту дз

2020-04-02 17:57 UTC, smirnov-vs commented
Дифф неполный, убедись, что все оформил верно

2020-04-02 18:25 UTC, piklin commented
fixed
Александра добавлю в ревьюверы как только он меня добавит

2020-04-05 16:44 UTC, smirnov-vs requested changes

2020-04-05 16:44 UTC, smirnov-vs commented on CMakeLists.txt
> +add_library(process STATIC src/Process.cpp include/Process.h)
зачем компилировать header?

2020-04-05 16:44 UTC, smirnov-vs commented on example/main.cpp
> +#define BIN_PATH "/bin/cat"
дефайн в спп коде

2020-04-05 16:44 UTC, smirnov-vs commented on example/main.cpp
> +    } catch(...) {
какое исключение тут ловится?

2020-04-05 16:44 UTC, smirnov-vs commented on example/main.cpp
> +        char readed_data[data.length()];
возможно переполнение стека

2020-04-05 16:44 UTC, smirnov-vs commented on example/main.cpp
> +        std::cout << std::string(readed_data) << std::endl;
почему бы тогда сразу строку не создать?

2020-04-05 16:44 UTC, smirnov-vs commented on src/Process.cpp
> +                throw std::exception();
утечка ресурсов

2020-04-05 16:44 UTC, smirnov-vs commented on src/Process.cpp
> +                throw std::exception();
как потом понять, что ошибка вылетела именно на этой строке?

2020-04-05 16:44 UTC, smirnov-vs commented on src/Process.cpp
> +            std::cerr << std::strerror(errno);
библиотека не общается с консолью

2020-04-05 16:44 UTC, smirnov-vs commented on src/Process.cpp
> +        return ::write(write_to_fd, data, len);
write возвращает не size_t

2020-04-05 16:44 UTC, smirnov-vs commented on src/Process.cpp
> +    }
это работает неверно

2020-04-05 16:44 UTC, smirnov-vs commented on src/Process.cpp
> +    }
еще нужно закрыть процесс

2020-04-05 16:44 UTC, smirnov-vs commented on src/Process.cpp
> +    }
это работает неверно

2020-04-05 16:51 UTC, piklin commented on example/main.cpp
> +    } catch(...) {
Из конструктора

2020-04-05 16:51 UTC, piklin commented on src/Process.cpp
> +                throw std::exception();
А как в таком случае лучше закрывать пайпы?

2020-04-05 16:53 UTC, piklin commented on src/Process.cpp
> +    }
Тогда я не совсем понимаю, как должен выглядеть метод readExact

2020-04-05 16:54 UTC, piklin commented on src/Process.cpp
> +    }
А как тогда правильно проверять, закрыт ли дескриптор? eof()?

2020-04-05 16:55 UTC, smirnov-vs commented on example/main.cpp
> +    } catch(...) {
почему тогда тут многоточие?)

2020-04-05 16:55 UTC, smirnov-vs commented on src/Process.cpp
> +                throw std::exception();
лучше всего через RAII

2020-04-05 16:56 UTC, smirnov-vs commented on src/Process.cpp
> +    }
readExact читает ровно столько байт, сколько у него попросили, если не вышло, тогда кидает ошибку

2020-04-05 16:56 UTC, smirnov-vs commented on src/Process.cpp
> +    }
read возвращает 0, когда та сторона закрылась

2020-04-05 16:56 UTC, smirnov-vs commented on src/Process.cpp
> +    }
но тут он зависнет, так как ты его дергаешь

2020-04-05 16:59 UTC, piklin commented on src/Process.cpp
> +    }
Можете натолкнуть на мысль, как тут правильнее сделать?

2020-04-05 17:01 UTC, smirnov-vs commented on src/Process.cpp
> +    }
тут не нужны сисколлы, просто узнаем с помощью этого метода факт, кончились ли данные

2020-04-05 17:31 UTC, piklin commented on example/main.cpp
> +        std::cout << std::string(readed_data) << std::endl;
Хмм, а как? read возвращает (char *), нам нужно куда то записать строку char'ов

2020-04-05 23:23 UTC, smirnov-vs commented on example/main.cpp
> +        std::cout << std::string(readed_data) << std::endl;
достаем буфер строки, записываем туда, все в документации языка

2020-04-07 07:03 UTC, piklin commented on example/main.cpp
> +        std::cout << std::string(readed_data) << std::endl;
Что-то я так и не смог нагуглить и придумать, как это сделать нормально

2020-04-07 16:50 UTC, piklin commented on src/Process.cpp
> +    }
Так и не понял, как это сделать, не считав данные, которые там могут быть

2020-04-07 16:51 UTC, piklin commented
Почти все переделал, кроме моментов в 2 дискуссиях. В них висят вопросы

2020-04-08 22:47 UTC, smirnov-vs commented on example/main.cpp
> +        std::cout << std::string(readed_data) << std::endl;
используй метод `.data()` для доступа к буферу

2020-04-08 22:48 UTC, smirnov-vs commented on src/Process.cpp
> +    }
как только пришел 0 после чтения надо пометить, что данные кончились

2020-04-08 22:51 UTC, smirnov-vs requested changes

2020-04-08 22:51 UTC, smirnov-vs commented on example/main.cpp
> +        auto *readed_data = new char[data.length()];
кто ответственный за память в этом дз?)

2020-04-08 22:51 UTC, smirnov-vs commented on src/Process.cpp
> +    }
есть утечка ресурсов

2020-04-08 22:51 UTC, smirnov-vs commented on src/Process.cpp
> +            std::cerr << std::strerror(errno);
такую ошибку не поймать

2020-04-08 22:51 UTC, smirnov-vs commented on src/Process.cpp
> +        this->~Process();
почему вызываем деструктор вручную?

2020-04-08 22:52 UTC, smirnov-vs commented on src/Process.cpp
> +        throw;
ловим, чтобы кинуть дальше?

2020-04-09 17:18 UTC, piklin commented on src/Process.cpp
> +        this->~Process();
Чтобы завершить процесс и почистить ресурсы. Или я не о том думаю?

2020-04-09 19:48 UTC, piklin commented on src/Process.cpp
> +        throw;
но если не обернуть в try-catch, то стек не раскрутится. Или нет?

2020-04-09 19:51 UTC, piklin commented
Пофиксил еще чуть-чуть, хотя вопросы по прежнему остаются

2020-04-14 23:10 UTC, smirnov-vs commented on src/Process.cpp
> +        throw;
стек раскручивается
такие базовые вещи нужно знать при поступлении к нам на курс

2020-04-14 23:10 UTC, smirnov-vs commented on src/Process.cpp
> +        this->~Process();
не о том, деструктор не вызывается вручную, стоит разобраться, в чем его суть

2020-04-14 23:13 UTC, smirnov-vs requested changes
работаем дальше

2020-04-14 23:13 UTC, smirnov-vs commented on include/Process.h
>  };
почему понадобилась эта сущность? Процесс сам по сути и является форком

2020-04-17 16:05 UTC, smirnov-vs requested changes

2020-04-17 16:05 UTC, smirnov-vs commented on src/Process.cpp
> +        }
попался

2020-04-17 20:09 UTC, piklin commented
Починил, должно стать чуть-чуть лучше

2020-04-19 16:46 UTC, smirnov-vs approved these changes

2020-04-27 17:26 UTC, merged