HW2
piklin/adv_cpp pull request #2
Opened 2020-04-12 22:33 UTC by piklin

2020-04-15 15:49 UTC, a-badin requested changes
Передаем аргументы по const ссылке, а не по значению
К переопределяемым функциям в классах добавляем override
Выделяем каждому потомку BaseLogger отдельный заголовочный файл и файл реализации 
Если будут сложности как разделить уровень лога от его строкового представления, напишите мне

2020-04-15 15:49 UTC, a-badin commented on CMakeLists.txt
> +target_include_directories(log PUBLIC src include)
У вас в src нет заголовочных файлов

2020-04-15 15:49 UTC, a-badin commented on hw_example/CMakeLists.txt
> +project(hw_example)
Обычно отдельный проект заводят под самостоятельный компонент. Который можно собрать отдельно от всего остального. У вас это не так, соответственно cmake_minimum_required и project можно не писать

2020-04-15 15:49 UTC, a-badin commented on include/Logger.h
> +    virtual const char* what() const noexcept;
вместо virtual пишут override, компилятор подстрахует вас если вы ошибетесь в сигнатуре метода

2020-04-15 15:49 UTC, a-badin commented on include/Logger.h
> +
Обычно выделяют отдельный namespace для библиотек

2020-04-15 15:49 UTC, a-badin commented on include/Logger.h
> +    std::string what_string;
приватные члены класса пишут с _ на конце или с префиксом m_ чтобы они не коллидировали с именами переменных и аргументов

2020-04-15 15:49 UTC, a-badin commented on include/Logger.h
> +    explicit Level(std::string);
Вы можете продумать такой интерфейс, что создать заведомо невалидный уровень лога и получить LoggerLevelError("no level"); будет невозможно

2020-04-15 15:49 UTC, a-badin commented on include/Logger.h
> +    std::map<std::string, size_t> levels =  {{"error", 0},
Level получается очень большим, каждый объект этого класса зачем-то таскает с собой копию вот этого словаря

2020-04-15 15:49 UTC, a-badin commented on src/Logger.cpp
> +    Level l(str_level);
Логика повтоярется - надо вынести в отдельный метод

2020-04-17 13:20 UTC, piklin commented
Исправил

2020-04-18 08:20 UTC, piklin commented
Залил фикс, вроде ничего не забыл

2020-04-18 08:34 UTC, a-badin approved these changes
Вторая домашняя работа засчитана на 5

2020-04-18 08:34 UTC, a-badin commented on include/Logger.h
> +    enum class Level : size_t {
Можно не указывать size_t, enum сам подберет наиболее подходящий тип

2020-04-18 08:34 UTC, a-badin commented on src/Logger.cpp
> +std::map<size_t, std::string> levels = {{0, "Error"},
А зачем size_t, у вас же тип Level,
`std::map<Level, std::string> levels {{Level::ERROR, "Error"}...`

2020-04-18 08:34 UTC, a-badin commented on src/Logger.cpp
> +log::BaseLoggerError::BaseLoggerError(const std::string &string) {
Вместо того, чтобы везде пистаь log:: просто открывается namespace log { как у заголовка и внутри определяются все необъодимые методы

2020-04-18 08:34 UTC, merged